# Generated by Django 4.0 on 2021-12-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0002_rename_catchprase_superhero_catchphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='villain',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
