# Generated by Django 4.0 on 2021-12-10 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0001_initial'),
        ('superheroes', '0003_superhero_villain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='villain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='villains.villain'),
        ),
    ]
