# Generated by Django 4.0 on 2021-12-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0001_initial'),
        ('superheroes', '0004_alter_superhero_villain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='villain',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='villains.villain'),
        ),
    ]
